Cadence o
lmyers427/CSCI441ProjectGroup1 pull request #46
Opened 2022-11-15 23:16 UTC by cadenceeo

2022-11-15 23:24 UTC, iEuphorius commented on views/support.ejs
> +    <form action="/login" method="POST" id="auth_form">
form action should go to the support router instead, not login. Also need a post route in the support router.

2022-11-15 23:26 UTC, iEuphorius requested changes
Swap form action to support and add a post request to support router.

2022-11-16 15:58 UTC, lmyers427 approved these changes

2022-11-16 16:43 UTC, iEuphorius approved these changes

2022-11-16 16:43 UTC, merged